name: example
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  logging: ^1.3.0
  oapi_codegen:
    path: ../oapi_codegen
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  dio: 5.7.0


dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  oapi_codegen_gen:
    path: ../oapi_codegen_gen

